name: selenoid

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v2
        
      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v2
        
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2
      
      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v2
        with:
          selenoid-start-arguments: "--browsers-json conf/browsers.json"
      
      - name: "selenoid"
        run: gradle test
